### ISSUE TITLE
Support spotify link URLs

### ISSUE THREAD

**Issue by himynameisjonas** [himynameisjonas/spotbot#4]
Need to support the regular http-urls since Spotify recently removed the `copy uri` option

**Comment by jorkas** [comment]
Great move, long live the web :+1:

**Comment by jorkas** [comment]
@himynameisjonas looks like they have added it back?
![screenshot 2015-03-16 21 53 22](https://cloud.githubusercontent.com/assets/39583/6676309/19c1d980-cc27-11e4-807c-2fdbb8f7ff13.png)

**Comment by himynameisjonas** [comment]
@jorkas haha!
But now you can choose whichever you want, Spotbot support both :)

**Comment by jorkas** [comment]
@himynameisjonas yes, that's AMAZING :heart:
