### ISSUE TITLE
Handle playlists with missing songs

### ISSUE THREAD

**Issue by ewal** [himynameisjonas/spotbot#6]
If a playlist has unplayable songs, none of the songs will be added to the playlist.

**Comment by himynameisjonas** [comment]
Do you have a example playlist that fails? (I wanted to ask you about a failing test case, but spotbot doesn't have any tests :sob:)

**Comment by ewal** [comment]
Try this one: spotify:user:creationrebel:playlist:0uqgZsxz6UDNSPQfHbpNVB

**Comment by himynameisjonas** [comment]
Cool, will look at this when I have time

**Comment by ewal** [comment]
:+1:
